apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_KEY: thisissecret
stringData:
  STRIPE_KEY: sk_test_51Ht0UFLqzutTJaglJBwGWSKDUoxkr9DNhQbhnDru2twmc3k2vXFKulsP79wAr3UGwVV7tKVGSsDbI9a6D2urgMMn00YrwUD0UC

